### ISSUE TITLE
Add more specific and verbose error when attachment doesn't exist on filesystem

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#161]
Currently, when I have in site.xml
```
 <attachment uri="non_exists" name="Migration-1-2.png"/>
```

Plugin version `6.0-rc2` says 
```
[INFO] attachment [non_exists] has not been updated (deploy skipped)
```

It confuses - why?
Message the same as for non-updated pages with parameter
```
       <deployState>
                                <active>true</active>
       </deployState>
```

**Comment by bsorrentino** [comment]
Hi @qwazer 

The log message template is:  **`'attachment <attachment uri> has not been updated (deploy skipped)'`**

This means that the attachment `<attachment uri>` has not been updated from last deploy

In your case ... being `<attachment uri>` = `non_exists` the message seems indicate the missing of file ...

**Comment by qwazer** [comment]
Yes. but I expect, that either
1) plugin fails because it cannot find the file
2) it will print warning message - cannot open the file by path 

So my proposal is to add the additional check when trying to open an attachment - if a file exists.

**Comment by qwazer** [comment]
The same problem with pages.

I have site.xml:

```xml
   <home name="ABC"
          uri="./markdown/00_parent.md" ignore-variables="true">
        <child name="Documenting your component" uri="markdown/non_existence.md" ignore-variables="true"/>
    </home>

    <label>documentation</label>
    <label>generated</label>
```

Execution `confluence-reporting-maven-plugin:6.0-rc2:deploy (site-deploy) ` gives me

```
[INFO] page [markdown/non_existence.md] has not been updated (deploy skipped)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.589 s
[INFO] Finished at: 2018-08-22T15:37:11+03:00
[INFO] Final Memory: 29M/287M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bsc.maven:confluence-reporting-maven-plugin:6.0-rc2:deploy (site-deploy) on project skeleton-docs: error generating report: null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.bsc.maven:confluence-reporting-maven-plugin:6.0-rc2:deploy (site-deploy) on project skeleton-docs: error generating report
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: error generating report
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.execute(ConfluenceDeployMojo.java:321)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NumberFormatException: null
        at java.lang.Long.parseLong(Long.java:552)
        at java.lang.Long.parseLong(Long.java:631)
        at org.bsc.maven.confluence.plugin.AbstractConfluenceMojo.generateChild(AbstractConfluenceMojo.java:400)
        at org.bsc.maven.confluence.plugin.AbstractConfluenceSiteMojo.generateChildren(AbstractConfluenceSiteMojo.java:248)
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.generateProjectReport(ConfluenceDeployMojo.java:623)
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.lambda$8(ConfluenceDeployMojo.java:637)
        at org.bsc.confluence.ConfluenceServiceFactory$MixedConfluenceService.call(ConfluenceServiceFactory.java:131)
        at org.bsc.maven.confluence.plugin.AbstractBaseConfluenceMojo.confluenceExecute(AbstractBaseConfluenceMojo.java:216)
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.generateProjectReport(ConfluenceDeployMojo.java:635)
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.execute(ConfluenceDeployMojo.java:306)
        ... 22 more


```

because page object is not updated, but when try to add labels on page it fails, pageId doesn't exist.

**Comment by bsorrentino** [comment]
Hi @qwazer 

As said `deployState` has been implemented  mostly to avoid re-publication during CI  process.

I think that, as workaround, it is enough to invoke `clean` before publish site.

I've to think about all the cases that imply a `deployState` invalidation
