### ISSUE TITLE
Proxy Settings not respected

### ISSUE THREAD

**Issue by sebpiller** [bsorrentino/maven-confluence-plugin#82]
Using org.bsc.maven:confluence-reporting-maven-plugin:4.2

It seems this bug: https://code.google.com/p/maven-confluence-plugin/issues/detail?id=26 is back with a slightly different message.

When I select the following in settings.xml, 

```xml
        <proxy>
            <active>true</active>
            <protocol>http</protocol>
            <host>proxy.company.com</host>
            <port>8080</port>
            <nonProxyHosts>127.0.0.1|localhost|*.company.com</nonProxyHosts>
        </proxy>
```

And whenever I try to invoke the plugin (Confluence is located on wiki.dep.company.com), it fails with the following trace (proxy answer):

```
org.codehaus.swizzle.confluence.ConfluenceException: HTTP server returned unexpected status: internal error - server connection terminated
	at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:934)
	at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:896)
	at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:882)
	at org.codehaus.swizzle.confluence.Confluence.login(Confluence.java:146)
	at org.codehaus.swizzle.confluence.ConfluenceFactory.createInstanceDetectingVersion(ConfluenceFactory.java:33)
	at org.bsc.maven.confluence.plugin.AbstractBaseConfluenceMojo.confluenceExecute(AbstractBaseConfluenceMojo.java:183)
	at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.generateProjectReport(ConfluenceDeployMojo.java:424)
	at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.execute(ConfluenceDeployMojo.java:257)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
```

Obviously, if I comment out the proxy section from settings.xml, it works as expected.

It seems to ignore (fail to parse?) the "nonProxyHosts" directive.

**Comment by bsorrentino** [comment]
Thanks for feedback

I'll check it soon 

From a first diagnosis the proxy infos set in maven are not used in confluence comm.

**Comment by bsorrentino** [comment]
The "noProxyHosts" is not taken in consideration in current implementation

so the problem cannot be related to it. Probably is your proxy that reset connection.

However I'm starting to work on take in consideration "noProxyHosts" settings

**Comment by sebpiller** [comment]
That's the point :) the fact that it ignores the nonProxyHost, make every request pass through the proxy, even those to local network machines (which is forbidden by our proxy rules)

**Comment by bsorrentino** [comment]
Hi 

i've deployed the version [4.3-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/bsc/maven/maven-confluence-parent/4.3-SNAPSHOT) with a fix (repository is https://oss.sonatype.org/content/repositories/snapshots/)

Please, could you test it and let me know ?

Thanks in advance

**Comment by sebpiller** [comment]
Hi,

I'm afraid, the fix seems not to work, I get the following error (using both Java 6 and Java 7):

{code}
[ERROR] Failed to execute goal org.bsc.maven:confluence-reporting-maven-plugin:4
.3-SNAPSHOT:deploy (default-cli) on project java-superpom: Execution default-cli
 of goal org.bsc.maven:confluence-reporting-maven-plugin:4.3-SNAPSHOT:deploy fai
led: An API incompatibility was encountered while executing org.bsc.maven:conflu
ence-reporting-maven-plugin:4.3-SNAPSHOT:deploy: java.lang.NoSuchMethodError: or
g.codehaus.swizzle.confluence.Confluence$ProxyInfo.<init>(Ljava/lang/String;ILja
va/lang/String;Ljava/lang/String;)V
{code}

**Comment by sebpiller** [comment]
Oh my bad, I did a stupid mistake when importing the artifact... 

Indeed, it works as expected. It just print the following stacktrace when running:

'''
[INFO] --- confluence-reporting-maven-plugin:4.3-SNAPSHOT:deploy (default-cli) @
 java-superpom ---
[INFO] executeReport isSnapshot = [true] isRemoveSnapshots = [true]
[ERROR] error creating site from model!
javax.xml.bind.UnmarshalException: unexpected element (uri:"http://code.google.c
om/p/maven-confluence-plugin", local:"site"). Expected elements are <{https://gi
thub.com/bsorrentino/maven-confluence-plugin}site>
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContex
t.handleEvent(UnmarshallingContext.java:647)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(
Loader.java:243)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(
Loader.java:238)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpe
ctedChildElement(Loader.java:105)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContex
t$DefaultRootLoader.childElement(UnmarshallingContext.java:1048)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContex
t._startElement(UnmarshallingContext.java:483)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContex
t.startElement(UnmarshallingContext.java:465)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startE
lement(SAXConnector.java:135)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Sour
ce)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unkn
own Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.s
canRootElementHook(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Sour
ce)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.un
marshal0(UnmarshallerImpl.java:203)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.un
marshal(UnmarshallerImpl.java:175)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:157)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:162)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:171)
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnm
arshallerImpl.java:189)
        at org.bsc.maven.confluence.plugin.AbstractConfluenceSiteMojo.createFrom
Model(AbstractConfluenceSiteMojo.java:343)
        at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.execute(Confluen
ceDeployMojo.java:217)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Site
 Labels
  java-superpom
  v0_0_2
'''
Which didn't print with the version 4.2

**Comment by bsorrentino** [comment]
Hi 

Thanks for feedback

About exception **form 4.3 I've updated the XML's namespace**, so goes in your **site xml file**  and update the namespace from 

` http://code.google.com/p/maven-confluence-plugin `

to 

` https://github.com/bsorrentino/maven-confluence-plugin `


Let me know so I'll arrange an official release

**Comment by sebpiller** [comment]
With the new namespace, everything works and I don't get an error anymore.

Seems good :)

**Comment by bsorrentino** [comment]
Great  

Thanks again :+1:
