### ISSUE TITLE
NPE in gitlog for partialy checkouted repos, that doesn't contain ref to "refs/remotes/origin/master"

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#88]
For example, use teamcity and build from not master branch:

```
java.lang.NullPointerException
    at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
    at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:863)
    at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:778)
    at com.github.qwazer.mavenplugins.gitlog.GitLogUtil.resolveCommitIdByTagName(GitLogUtil.java:67)
    at com.github.qwazer.mavenplugins.gitlog.GitLogUtil.extractJiraIssues(GitLogUtil.java:91)
    at com.github.qwazer.mavenplugins.gitlog.GitLogUtil.extractJiraIssuesByVersion(GitLogUtil.java:116)

```

**Comment by bsorrentino** [comment]
Hi @qwazer 

Such bug is still valid ?

**Comment by qwazer** [comment]
I think no. Nobody complains.
