### ISSUE TITLE
finding value for spaceKey (and parentPageTitle)

### ISSUE THREAD

**Issue by gartcimore** [bsorrentino/maven-confluence-plugin#95]
Hello,
I'm having a problem configuring the plugin correctly.
Here is an extract from my multi modules project : 
https://gist.github.com/gartcimore/a8be6756dd73c0f89185
Maybe the end point is incorrect ? How do I know/found what is the correct end point for my server ?

I've got the following problem when I use 
**mvn confluence-reporting:deploy**

`[DEBUG]   (f) removeSnapshots = false
[DEBUG]   (f) serverId = intranet.myserver.com
[DEBUG]   (f) siteDescriptor = C:\mercurial\depots\ucs\ucs-tng\src\site\confluence\site.xml
[DEBUG]   (f) spaceKey = RP
[DEBUG]   (f) templateWiki = C:\mercurial\depots\ucs\ucs-tng\src\site\confluence\template.wiki
[DEBUG]   (s) title = my-site-generation-test
[DEBUG]   (f) webAccessUrl = http://urlToCI
[DEBUG]   (f) wikiFilesExt = .wiki
[DEBUG] -- end configuration --
[INFO] executeReport isSnapshot = [true] isRemoveSnapshots = [false]
Site
 Labels
  test
  ucs
 Page: my-site-generation-test - jar:file:/C:/tools/maven_repo/org/bsc/maven/confluence-reporting-maven-plugin/4.5/confluence-reporting-maven-plugin-4.5.jar!/defaultTemplate.confluence
[DEBUG] SSLCertificate{ignore:true,hostnameVerifierClass:'null',trustManagerClass:'null,}
[INFO] Confluence version [5.5.4-5517] development version [false]
[ERROR] has been imposssible connect to confluence due exception
org.codehaus.swizzle.confluence.ConfluenceException: java.lang.Exception: com.atlassian.confluence.rpc.RemoteException: You're not allowed to view that page, or it does not exist.
	at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:971)
	at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:933)
	at org.codehaus.swizzle.confluence.Confluence.call(Confluence.java:919)
	at org.codehaus.swizzle.confluence.Confluence.getPage(Confluence.java:278)
	at org.bsc.maven.plugin.confluence.ConfluenceUtils.getOrCreatePage(ConfluenceUtils.java:142)
	at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo$1.execute(ConfluenceDeployMojo.java:444)
	at org.bsc.maven.confluence.plugin.AbstractBaseConfluenceMojo.confluenceExecute(AbstractBaseConfluenceMojo.java:189)
	at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.generateProjectReport(ConfluenceDeployMojo.java:428)
	at org.bsc.maven.confluence.plugin.ConfluenceDeployMojo.execute(ConfluenceDeployMojo.java:258)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`

![confluence_space](https://cloud.githubusercontent.com/assets/14348117/13957326/608d5002-f04c-11e5-9245-4fa6dab178fa.png)

**Comment by gartcimore** [comment]
Found this [https://developer.atlassian.com/confdev/confluence-rest-api/confluence-xml-rpc-and-soap-apis](atlassian page) about xml rpc api being deprecated for confluence 5.5. We use confluence 5.5.4 and I guess that maybe the api isn't enabled.
Are there any plan to support the [https://docs.atlassian.com/atlassian-confluence/REST/latest/](REST Api) provided with confluence 5.5

**Comment by bsorrentino** [comment]
Hi , you right  **"xml rpc api has been deprecated"** but still works. What I suggest you is to check for space permission

However from your gist I don't understand if you're using "single page" or "site"  deployment. Moreover i suggest you to specify ```parentPageTitle``` explicitly.

About move to REST it's not planned yet ... but it is unavoidable (probably for release 5.0)

**Comment by bsorrentino** [comment]
refer to [Issue#96](https://github.com/bsorrentino/maven-confluence-plugin/issues/96)

**Comment by gartcimore** [comment]
Yes, the xml rpc api seems to be still enabled.

> However from your gist I don't understand if you're using "single page" or "site" deployment
I'm not sure of what I'm doing :)
Ideally I would like to upload site definition and some specific pages. My configuration may be absolutely wrong

**Comment by gartcimore** [comment]
Yes, the xml rpc api seems to be still enabled.

> However from your gist I don't understand if you're using "single page" or "site" deployment
I'm not sure of what I'm doing :)
Ideally I would like to upload site definition and some specific pages. My configuration may be absolutely wrong
